name: APK Inspector
description: Inspect the APK and extract the version

inputs:
  package_name:
    description: The package name of the APK
    required: true
  force_update:
    description: Force update the version
    required: false
    default: 'false'
  version_file:
    description: The file to save the version to
    required: true

outputs:
  skip:
    description: Whether to skip the APK inspection
    value: ${{ steps.get-version.outputs.skip }}
  version:
    description: The version of the APK
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.24'

    - name: Check the APK version
      id: get-version
      shell: bash
      run: ./scripts/extract_version.sh ${{ inputs.package_name }} ${{ inputs.force_update }} ${{ inputs.version_file }}
