name: Get Version
description: Get the version of the server

inputs:
  server:
    description: The server to update the version for
    required: true
  force_update:
    description: Force update the version
    required: false
    default: 'false'
  version_file:
    description: The file to save the version to
    required: true

outputs:
  skip:
    description: Whether to skip the version check
    value: ${{ steps.get-version.outputs.skip }}
  version:
    description: The version of the server resources
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.24'

    - name: Check the server resources version
      id: get-version
      shell: bash
      run: ./scripts/extract_version.sh ${{ inputs.server }} ${{ inputs.force_update }} ${{ inputs.version_file }}
