name: Update Global Version

on:
  schedule:
    # Check every 2 hours from 1am to 14/2 (12:00am to 7:00pm) every day.
    - cron: "0 1-14/2 * * *"
  workflow_dispatch:
    inputs:
      force_update:
        type: boolean
        required: false
        default: false
        description: Force update the game version

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: ./.github/workflows/update-server.yml
    with:
      server: global
      force_update: ${{ inputs.force_update || false }}
